### ISSUE TITLE
Accessing and Subsetting Error

### ISSUE THREAD

**Issue by AmBarry** [limix/pandas-plink#16]
Nice package!
I tried to implement the example and it works except when I want to print the values using .sel().values. I am using python 3.8 on a cluster.
Here is my code and the error.
Thanks.
```python
import scipy
from scipy import linalg
import numpy as np
#import csv
import sklearn
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import LassoCV
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
import matplotlib.pyplot as plt
import pandas
from pandas_plink import read_plink1_bin
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
geno = read_plink1_bin("~/plink_file/EUR_100k.bed",
                          "~/plink_file/EUR_100k.bim",
                          "~/plink_file/EUR_100k.fam")
print(geno)
Coordinates:
  * sample   (sample) object 'id2_0' 'id2_1' 'id2_2' ... 'id2_99998' 'id2_99999'
  * variant  (variant) object '22_rs375684679' ... '22_rs370652263'
    fid      (sample) <U9 'id1_0' 'id1_1' 'id1_2' ... 'id1_99998' 'id1_99999'
    iid      (sample) <U9 'id2_0' 'id2_1' 'id2_2' ... 'id2_99998' 'id2_99999'
    father   (sample) <U1 '0' '0' '0' '0' '0' '0' ... '0' '0' '0' '0' '0' '0'
    mother   (sample) <U1 '0' '0' '0' '0' '0' '0' ... '0' '0' '0' '0' '0' '0'
    gender   (sample) <U1 '0' '0' '0' '0' '0' '0' ... '0' '0' '0' '0' '0' '0'
    trait    (sample) float64 1.0 1.0 1.0 1.0 1.0 1.0 ... 1.0 1.0 1.0 1.0 1.0
    chrom    (variant) <U2 '22' '22' '22' '22' '22' ... '22' '22' '22' '22' '22'
    snp      (variant) <U11 'rs375684679' 'rs376238049' ... 'rs370652263'
    cm       (variant) float64 0.0 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0 0.0
    pos      (variant) int64 16052167 16052962 16052986 ... 51237364 51237712
    a0       (variant) <U50 'AAAAC' 'T' 'A' 'T' 'A' 'A' ... 'A' 'AT' 'C' 'G' 'A'
    a1       (variant) <U51 'A' 'C' 'C' 'A' 'C' 'C' ... 'T' 'G' 'A' 'T' 'A' 'G'
print(geno.sel(sample="id2_1", variant="22_rs370652263").values)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/ENV/lib/python3.8/site-packages/xarray/core/dataarray.py", line 567, in values
    return self.variable.values
  File "/home/user/ENV/lib/python3.8/site-packages/xarray/core/variable.py", line 448, in values
    return _as_array_or_item(self._data)
  File "/home/user/ENV/lib/python3.8/site-packages/xarray/core/variable.py", line 254, in _as_array_or_item
    data = np.asarray(data)
  File "/home/user/ENV/lib/python3.8/site-packages/numpy/core/_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/home/user/ENV/lib/python3.8/site-packages/dask/array/core.py", line 1336, in __array__
    x = self.compute()
  File "/home/user/ENV/lib/python3.8/site-packages/dask/base.py", line 166, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/user/ENV/lib/python3.8/site-packages/dask/base.py", line 438, in compute
    dsk = collections_to_dsk(collections, optimize_graph, **kwargs)
  File "/home/user/ENV/lib/python3.8/site-packages/dask/base.py", line 217, in collections_to_dsk
    _opt_list.append(opt(_graph_and_keys[0], _graph_and_keys[1], **kwargs))
  File "/home/user/ENV/lib/python3.8/site-packages/dask/array/optimization.py", line 46, in optimize
    dsk = ensure_dict(dsk)
  File "/home/user/ENV/lib/python3.8/site-packages/dask/utils.py", line 1033, in ensure_dict
    result.update(dd)
  File "/home/user/ENV/lib/python3.8/_collections_abc.py", line 720, in __iter__
    yield from self._mapping
  File "/home/user/ENV/lib/python3.8/site-packages/dask/blockwise.py", line 229, in __iter__
    return iter(self._dict)
  File "/home/user/ENV/lib/python3.8/site-packages/dask/blockwise.py", line 212, in _dict
    dsk, _ = fuse(self.dsk, [self.output])
  File "/home/user/ENV/lib/python3.8/site-packages/dask/optimization.py", line 496, in fuse
    if not config.get("optimization.fuse.active"):
  File "/home/user/ENV/lib/python3.8/site-packages/dask/config.py", line 459, in get
    result = result[k]
KeyError: 'optimization'

```

**Comment by horta** [comment]
Thanks a lot for using it!

It seems that the problem is with the configuration of your dask package: https://docs.dask.org/en/latest/configuration.html

It might help figured it out by doinng

```
import dask
print(dask.config.config)
```
